------------------------------------------------------------------------
-- Night's Farmtracker - Localization
-- Default: English. Override per locale below.
------------------------------------------------------------------------
local _, ns = ...
local L = {}
ns.L = L

------------------------------------------------------------------------
-- English (default)
------------------------------------------------------------------------
-- Main frame
L["start_tracking"]    = "Start tracking"
L["pause_tracking"]    = "Pause tracking"
L["reset_session"]     = "Reset session"
L["reset_desc"]        = "Save to history, clear items & timer"
L["reset_shift_hint"]  = "Shift+Click: reset without saving to history"
L["session_history"]   = "Session History"
L["settings"]          = "Settings"
L["collapse"]          = "Collapse"
L["expand"]            = "Expand"
L["close"]             = "Close"
L["gathering_active"]  = "Gathering... loot will appear here"
-- Help tooltip
L["help_categories"]   = "Categories:"
L["help_cat_click"]    = "  Click to expand/collapse"
L["help_cat_rclick"]   = "  Shift+Right-click to exclude"
L["help_items"]        = "Items:"
L["help_item_hover"]   = "  Hover for item tooltip"
L["help_item_rclick"]  = "  Shift+Right-click to stop tracking"
L["help_gold"]         = "Gold overview:"
L["help_gold_click"]   = "  Click total gold (footer) to toggle breakdown"
L["help_reset"]        = "Reset:"
L["help_reset_shift"]  = "  Shift+Click to reset without saving to history"
-- History
L["delete_session"]    = "Delete this session"
L["delete_all"]        = "Delete all saved sessions"
L["clear_all"]         = "Clear All"
L["no_sessions"]       = "No sessions saved yet"
L["item_singular"]     = "%d item"
L["item_plural"]       = "%d items"
L["sessions_summary"]  = "%d session across %d day (max %d)"
L["sessions_summary_pl"] = "%d sessions across %d days (max %d)"
L["looted_gold"]       = "Direct"
L["merge_day_btn"]     = "Merge"
L["merge_day_tooltip"] = "Merge all sessions of this day into one"
L["merge_day_confirm"] = "Merge all %d sessions of %s into one? This cannot be undone."
-- Settings
L["settings_title"]    = "Night's Farmtracker — Settings"
L["ah_source"]         = "AH Price Source"
L["ah_auto"]           = "Auto (best available)"
L["ah_auctionator"]    = "Auctionator"
L["ah_tsm"]            = "TradeSkillMaster (TSM)"
L["ah_none"]           = "None (vendor only)"
L["not_installed"]     = "(not installed)"
L["tsm_source"]        = "TSM Price Source"
L["tsm_hint"]          = "Click to cycle: DBMarket · DBRegionMarketAvg · DBMinBuyout"
L["display"]           = "Display"
L["gold_per_hour"]     = "Gold / hour"
L["gold_per_min"]      = "Gold / min"
L["gold_display_classic"] = "Classic gold display (icons)"
L["gold_display_modern"]  = "Modern gold display (colored text)"
-- Modern gold display suffixes
L["coin_gold"]   = "g"
L["coin_silver"] = "s"
L["coin_copper"] = "c"
L["minimap_button"]    = "Show minimap button"
L["reload_required"]   = "Reload required."
-- Categories
L["cat_junk"]       = "Junk"
L["cat_gear"]       = "Equipment"
L["cat_pets"]       = "Pets"
L["cat_mounts"]     = "Mounts"
-- Category row tooltips
L["cat_tip_click"]         = "Click to expand/collapse"
L["cat_tip_shift_rclick"]  = "Shift+Right-click to exclude"
L["item_tip_shift_rclick"] = "Shift+Right-click to stop tracking"
-- Minimap
L["mm_toggle"]   = "Click to toggle window"
L["mm_settings"] = "Right-click for settings"
L["mm_drag"]     = "Drag to reposition"
-- Gold rate suffix
L["rate_hr"]  = "/hr"
L["rate_min"] = "/min"
-- Gold overview tooltip
L["gold_overview"] = "Gold Overview"
L["gold_items"]    = "Items"
L["gold_total"]    = "Total"
-- Settings
L["tracking"]                 = "Tracking"
L["session_history_enabled"]  = "Save session history"
L["split_trade_goods"]        = "Split trade goods by subtype"
L["merge_daily_sessions"]     = "Merge same-day sessions automatically"
L["vendor_filter_enabled"]    = "Enable Vendor-Only Filter"
L["log_window_enabled"]       = "Enable loot log window"
L["ah_auto_info"]             = "Prefers Auctionator, falls back to TSM"
L["tsm_custom"]               = "Custom TSM expression (overrides above)"
-- Vendor-only filter
L["filter_title"]             = "Vendor-Only Filter"
L["filter_button"]            = "Vendor-Only Filter"
L["filter_drop_hint"]         = "Drop item here"
L["filter_list_empty"]        = "No items in filter yet"
L["filter_tip_shift_rclick"]  = "  Shift+Right-click to remove"
-- Loot log
L["log_title"]                = "Loot Log"
L["log_empty"]                = "No items yet"

------------------------------------------------------------------------
-- German (deDE)
------------------------------------------------------------------------
if GetLocale() == "deDE" then
    L["start_tracking"]    = "Tracking starten"
    L["pause_tracking"]    = "Tracking pausieren"
    L["reset_session"]     = "Session zurücksetzen"
    L["reset_desc"]        = "In Verlauf speichern, Items & Timer leeren"
    L["reset_shift_hint"]  = "Shift-Klick: Zurücksetzen ohne Speichern im Verlauf"
    L["session_history"]   = "Session-Verlauf"
    L["settings"]          = "Einstellungen"
    L["collapse"]          = "Einklappen"
    L["expand"]            = "Ausklappen"
    L["close"]             = "Schließen"
    L["gathering_active"]  = "Sammle... Beute erscheint hier"
    L["help_categories"]   = "Kategorien:"
    L["help_cat_click"]    = "  Klick: ein-/ausklappen"
    L["help_cat_rclick"]   = "  Shift-Rechtsklick: ausschliessen"
    L["help_items"]        = "Items:"
    L["help_item_hover"]   = "  Hover: Item-Tooltip"
    L["help_item_rclick"]  = "  Shift-Rechtsklick: nicht tracken"
    L["help_gold"]         = "Gold-Übersicht:"
    L["help_gold_click"]   = "  Klick auf Gesamtgold (unten) zeigt Aufschlüsselung"
    L["help_reset"]        = "Zurücksetzen:"
    L["help_reset_shift"]  = "  Shift-Klick: Zurücksetzen ohne Speichern im Verlauf"
    L["delete_session"]    = "Session löschen"
    L["delete_all"]        = "Alle Sessions löschen"
    L["clear_all"]         = "Alles löschen"
    L["no_sessions"]       = "Keine Sessions gespeichert"
    L["item_singular"]     = "%d Item"
    L["item_plural"]       = "%d Items"
    L["sessions_summary"]    = "%d Session über %d Tag (max %d)"
    L["sessions_summary_pl"] = "%d Sessions über %d Tage (max %d)"
    L["looted_gold"]       = "Direkt"
    L["merge_day_btn"]     = "Merge"
    L["merge_day_tooltip"] = "Alle Sessions dieses Tages zusammenführen"
    L["merge_day_confirm"] = "Alle %d Sessions von %s zusammenführen? Kann nicht rückgängig gemacht werden."
    L["settings_title"]    = "Night's Farmtracker — Einstellungen"
    L["ah_source"]         = "AH-Preisquelle"
    L["ah_auto"]           = "Automatisch (beste verfügbare)"
    L["ah_auctionator"]    = "Auctionator"
    L["ah_tsm"]            = "TradeSkillMaster (TSM)"
    L["ah_none"]           = "Keine (nur Händlerpreis)"
    L["not_installed"]     = "(nicht installiert)"
    L["tsm_source"]        = "TSM-Preisquelle"
    L["tsm_hint"]          = "Klicken zum Wechseln: DBMarket · DBRegionMarketAvg · DBMinBuyout"
    L["display"]           = "Anzeige"
    L["gold_per_hour"]     = "Gold / Stunde"
    L["gold_per_min"]      = "Gold / Minute"
    L["gold_display_classic"] = "Klassische Gold-Anzeige (Icons)"
    L["gold_display_modern"]  = "Moderne Gold-Anzeige (farbiger Text)"
    -- Modern gold display suffixes
    L["coin_gold"]   = "g"
    L["coin_silver"] = "s"
    L["coin_copper"] = "k"
    L["minimap_button"]    = "Minimap-Button anzeigen"
    L["reload_required"]   = "Neustart erforderlich."
    L["cat_junk"]          = "Müll"
    L["cat_gear"]          = "Ausrüstung"
    L["cat_pets"]          = "Haustiere"
    L["cat_mounts"]        = "Reittiere"
    -- Tooltips
    L["cat_tip_click"]         = "Klick zum Ein-/Ausklappen"
    L["cat_tip_shift_rclick"]  = "Shift-Rechtsklick: Ausschliessen"
    L["item_tip_shift_rclick"] = "Shift-Rechtsklick: Nicht mehr tracken"
    -- Minimap
    L["mm_toggle"]   = "Klick zum Ein-/Ausblenden"
    L["mm_settings"] = "Rechtsklick für Einstellungen"
    L["mm_drag"]     = "Ziehen zum Verschieben"
    -- Gold rate suffix
    L["rate_hr"]  = "/Std"
    L["rate_min"] = "/Min"
    -- Gold overview tooltip
    L["gold_overview"] = "Gold-Übersicht"
    L["gold_items"]    = "Items"
    L["gold_total"]    = "Gesamt"
    -- Settings
    L["tracking"]                = "Tracking"
    L["session_history_enabled"] = "Session-Verlauf speichern"
    L["split_trade_goods"]       = "Handwerksmaterialien nach Typ aufteilen"
    L["merge_daily_sessions"]    = "Sessions desselben Tages automatisch zusammenführen"
    L["vendor_filter_enabled"]   = "Vendor-Only-Filter aktivieren"
    L["log_window_enabled"]      = "Verlaufsfenster aktivieren"
    L["ah_auto_info"]            = "Bevorzugt Auctionator, fällt auf TSM zurück"
    L["tsm_custom"]              = "Eigener TSM-Ausdruck (überschreibt oben)"
    -- Vendor-only filter
    L["filter_title"]            = "Vendor-Only-Filter"
    L["filter_button"]           = "Vendor-Only-Filter"
    L["filter_drop_hint"]        = "Item hier rein ziehen"
    L["filter_list_empty"]       = "Noch keine Items im Filter"
    L["filter_tip_shift_rclick"] = "  Shift-Rechtsklick: Entfernen"
    -- Verlaufsfenster
    L["log_title"]               = "Verlaufsfenster"
    L["log_empty"]                = "Noch keine Items"
end