------------------------------------------------------------------------
-- Night's Farmtracker - Localization
-- Default: English. Override per locale below.
------------------------------------------------------------------------
local _, ns = ...
local L = {}
ns.L = L

------------------------------------------------------------------------
-- English (default)
------------------------------------------------------------------------
-- Month names (index 1-12), used for month grouping in Session History
L.MONTH_NAMES = {
    "January","February","March","April","May","June",
    "July","August","September","October","November","December",
}
-- Main frame
L["start_tracking"]    = "Start tracking"
L["pause_tracking"]    = "Pause tracking"
L["reset_session"]     = "Reset session"
L["reset_desc"]        = "Save to history, clear items & timer"
L["reset_shift_hint"]  = "Shift+Click: reset without saving to history"
L["session_history"]   = "Session History"
L["settings"]          = "Settings"
L["collapse"]          = "Collapse"
L["expand"]            = "Expand"
L["close"]             = "Close"
L["gathering_active"]  = "Gathering... loot will appear here"
-- Help tooltip
L["help_categories"]   = "Categories:"
L["help_cat_click"]    = "  Click to expand/collapse"
L["help_cat_rclick"]   = "  Shift+Right-click to exclude"
L["help_items"]        = "Items:"
L["help_item_hover"]   = "  Hover for item tooltip"
L["help_item_rclick"]  = "  Shift+Right-click to stop tracking"
L["help_gold"]         = "Gold overview:"
L["help_gold_click"]   = "  Click total gold (footer) to toggle breakdown"
L["help_reset"]        = "Reset:"
L["help_reset_shift"]  = "  Shift+Click to reset without saving to history"
L["help_histlog"]       = "Session History / Loot Log:"
L["help_histlog_left"]  = "  Left-click: Session History"
L["help_histlog_right"] = "  Right-click: Loot Log"
L["help_filter"]        = "Filter / Blacklist:"
L["help_filter_left"]   = "  Left-click: Vendor-Only Filter"
L["help_filter_right"]  = "  Right-click: Blacklist"
L["help_title"]         = "Night's Farmtracker — Info"
L["help_fishing"]       = "Fishing:"
L["help_fishing_hint"]  = "  Enable Venom Tracker / Lure Bar in Settings -> Fishing"
L["help_export"]        = "Data Export:"
L["help_export_hint"]   = "  Settings -> Data Export, or /nft export"
L["hist_log_left_hint"]  = "Left-click: Session History"
L["hist_log_right_hint"] = "Right-click: Loot Log"
-- History
L["delete_session"]    = "Delete this session"
L["delete_all"]        = "Delete all saved sessions"
L["clear_all"]         = "Clear All"
L["reset_addon"]       = "Reset to Default"
L["reset_addon_confirm"] = "Reset the entire addon to default? This deletes ALL saved data (settings, session history, Vendor-Only filter, Blacklist) and cannot be undone. The UI will reload."
L["clear_all_history_confirm"] = "Delete all saved session history? This cannot be undone."
L["no_sessions"]       = "No sessions saved yet"
L["session_reset_migration_text"]  = "Night's Farmtracker now shows the exact item you looted in tooltips (correct item level for scaling gear). Sessions saved before this update are missing that info and will keep showing generic tooltips for equipment.\n\nClear all saved session history now to start fresh?"
L["tooltip_scaling_unknown"] = "Exact item level unknown (saved before this update)"
L["item_singular"]     = "%d item"
L["item_plural"]       = "%d items"
L["tip_priced_ah"]     = "Priced at AH: %d"
L["tip_priced_vendor"] = "Priced at vendor: %d"
L["sessions_summary"]  = "%d session"
L["sessions_summary_pl"] = "%d sessions"
L["looted_gold"]       = "Direct"
L["merge_day_btn"]     = "Merge"
L["merge_day_tooltip"] = "Merge all sessions of this day into one"
L["merge_day_confirm"] = "Merge all %d sessions of %s into one? This cannot be undone."
L["month_summary_tooltip"] = "Shift+Click: Month summary"
L["detail_duration"]  = "Duration"
L["delete_month"]        = "Delete this month"
L["delete_month_confirm"] = "Delete all %d sessions of %s? This cannot be undone."
-- Settings
L["settings_title"]    = "Night's Farmtracker — Settings"
L["ah_source"]         = "AH Price Source"
L["ah_auto"]           = "Auto (best available)"
L["ah_auctionator"]    = "Auctionator"
L["ah_oribos"]         = "Oribos Exchange"
L["ah_tsm"]            = "TradeSkillMaster (TSM)"
L["ah_none"]           = "None (vendor only)"
L["not_installed"]     = "(not installed)"
L["gear_ah_threshold_hint"] = "Equipment only uses its AH price once it reaches this amount; below it, vendor price is shown (0 = disabled). Use the gear icon to choose which Equipment categories this applies to"
L["gear_ah_threshold_sound"] = "Play sound when Equipment reaches this threshold"
L["gear_ah_threshold_config_title"] = "Threshold applies to:"
L["gear_ah_threshold_config_tip"] = "Choose which Equipment categories the threshold applies to. Unchecked categories always use the higher of AH and vendor price."
L["gold_suffix"]       = "g"
L["tsm_hint"]          = "Click to cycle: DBMarket · DBRegionMarketAvg · DBMinBuyout"
L["display"]           = "Display"
L["theme_default"]     = "Default"
L["theme_void"]        = "Void"
L["theme_silvermoon"]  = "Silvermoon"
L["theme_fel"]         = "Fel"
L["theme_frost"]       = "Frost"
L["theme_bloodmoon"]   = "Bloodmoon"
L["theme_molten"]      = "Molten"
L["theme_emerald"]     = "Emerald"
L["theme_arcane"]      = "Arcane"
L["theme_bronze"]      = "Bronze"
L["theme_plague"]      = "Plague"
L["theme_nether"]      = "Nether"
L["theme_argent"]      = "Argent"
L["theme_default_desc"]    = "Teal"
L["theme_void_desc"]       = "Purple"
L["theme_silvermoon_desc"] = "Warm Gold"
L["theme_fel_desc"]        = "Toxic Green"
L["theme_frost_desc"]      = "Ice Blue"
L["theme_bloodmoon_desc"]  = "Blood Red"
L["theme_molten_desc"]     = "Lava Orange"
L["theme_emerald_desc"]    = "Emerald Green"
L["theme_arcane_desc"]     = "Magenta"
L["theme_bronze_desc"]     = "Bronze"
L["theme_plague_desc"]     = "Sickly Green"
L["theme_nether_desc"]     = "Deep Teal"
L["theme_argent_desc"]     = "Holy Gold"
L["gold_per_hour"]     = "Gold / hour"
L["gold_per_min"]      = "Gold / min"
L["session_length_hint"] = "Session length: the timer counts down and pauses automatically at 0 (0 = off)"
L["minutes_suffix"]    = "min"
L["session_length_reached"] = "Session length reached - tracking paused."
L["session_length_reached_resume"] = "Session length reached. Reset to start a new session, or change the length in Settings."
L["gold_display_classic"] = "Classic gold display (icons)"
L["gold_display_modern"]  = "Modern gold display (colored text)"
-- Modern gold display suffixes
L["coin_gold"]   = "g"
L["coin_silver"] = "s"
L["coin_copper"] = "c"
L["minimap_button"]    = "Show minimap button"
L["reload_required"]   = "Reload required."
-- Categories
L["cat_junk"]       = "Junk"
L["junk_merged_name"] = "Trash"
L["cat_gear"]       = "Equipment"
L["cat_gear_boe"]   = "Equipment (BoE)"
L["cat_gear_boa"]   = "Equipment (BoA)"
L["cat_gear_soul"]  = "Equipment (Soulbound)"
L["cat_gear_cosmetic"] = "Equipment (Cosmetic)"
L["cat_pets"]       = "Pets"
L["cat_mounts"]     = "Mounts"
-- Category row tooltips
L["cat_tip_click"]         = "Click to expand/collapse"
L["cat_tip_shift_rclick"]  = "Shift+Right-click to exclude"
L["item_tip_shift_rclick"] = "Shift+Right-click to stop tracking"
-- Minimap
L["mm_toggle"]   = "Click to toggle window"
L["mm_settings"] = "Right-click for settings"
L["mm_drag"]     = "Drag to reposition"
-- Gold rate suffix
L["rate_hr"]  = "/hr"
L["rate_min"] = "/min"
-- Gold overview tooltip
L["gold_overview"] = "Gold Overview"
L["gold_items"]    = "Items"
L["gold_total"]    = "Total"
-- Settings
L["sec_categories"]           = "Categories & Grouping"
L["sec_filters"]              = "Filters"
L["session_history_enabled"]  = "Save session history"
L["split_trade_goods"]        = "Split trade goods by subtype"
L["split_gear_by_binding"]    = "Split equipment by binding (BoE/BoA/Soulbound)"
L["merge_junk_entries"]       = "Merge Junk into one entry (\"Plunder\")"
L["merge_daily_sessions"]     = "Merge same-day sessions automatically"
L["session_history_mode"]         = "Session history mode:"
L["session_history_mode_compact"] = "Compact (merge past months)"
L["session_history_mode_full"]    = "Full (keep every session)"
L["compact_history_confirm"]      = "Merge all past months into one entry each now? This cannot be undone."
L["vendor_filter_enabled"]    = "Enable Vendor-Only Filter"
L["blacklist_enabled"]        = "Enable Blacklist"
L["log_window_enabled"]       = "Enable loot log window"
L["ah_auto_info"]             = "Prefers Auctionator, then Oribos Exchange, then TSM"
L["tsm_custom"]               = "Custom TSM expression (overrides above)"
-- Profiles
L["sec_profiles"]             = "Profiles"
L["profile_new"]              = "New"
L["profile_copy"]             = "Copy"
L["profile_rename"]           = "Rename"
L["profile_delete"]           = "Delete"
L["profile_new_prompt"]       = "New profile name:"
L["profile_copy_prompt"]      = "Name for the copy:"
L["profile_rename_prompt"]    = "Rename profile to:"
L["profile_delete_confirm"]   = "Delete profile \"%s\"? This cannot be undone."
L["profile_delete_hint"]      = "Delete an unused profile (doesn't affect your active one):"
L["profile_delete_none"]      = "— none —"
-- Vendor-only filter
L["filter_title"]             = "Vendor-Only Filter"
L["filter_button"]            = "Filter"
L["filter_drop_hint"]         = "Drop item here"
L["filter_list_empty"]        = "No items in filter yet"
L["filter_clear_all_confirm"] = "Remove all items from the Vendor-Only Filter? This cannot be undone."
L["filter_tip_shift_rclick"]  = "  Shift+Right-click to remove"
L["filter_categories_title"]  = "Vendor-Only Categories"
L["filter_ah_expansions_title"] = "AH Price by Expansion"
L["filter_ah_expansions_hint"]  = "Check expansions to show AH price for. Unchecked expansions use vendor price. Nothing checked = filter off."
L["filter_left_hint"]         = "Left-click: Vendor-Only Filter"
L["filter_right_hint"]        = "Right-click: Blacklist"
L["blacklist_title"]          = "Blacklist"
L["blacklist_list_empty"]     = "No items blacklisted yet"
L["blacklist_clear_all_confirm"] = "Remove all items from the Blacklist? This cannot be undone."
L["blacklist_categories_title"] = "Blacklisted Categories"
-- Loot log
L["log_title"]                = "Loot Log"
L["log_empty"]                = "No items yet"
-- Fishing
L["sec_fishing"]              = "Fishing"
L["venom_tracker_enabled"]    = "Enable Coiled Huntress Venom Tracker"
L["venom_tracker_title"]      = "Venom Tracker"
L["venom_tracker_hint"]       = "Drag to move · Right-click to reset · /nft venom to toggle"
L["bait_frame_enabled"]       = "Enable Fishing Lure Bar"
L["lockout_enabled"]          = "Show instance lockout counter below the main window"
L["lockout_count"]            = "Lockout: %d/%d"
L["lockout_tooltip_title"]    = "Instance lockout: %d/%d"
L["lockout_reset_hint"]       = "Click to reset instances. Each entry shows when it expires (1 hour after the reset)."
L["bait_frame_hint"]          = "Click to use · Right-click to remove · Drag a lure here to add it"
L["bait_frame_empty"]         = "Drag a lure here to add it"
L["bait_frame_rejected"]      = "Doesn't look like a fishing lure. Hold Shift to add it anyway."
L["bait_no_active_buff"]      = "No active lure"
-- Data Export
L["sec_export"]               = "Data Export"
L["export_hint"]              = "Copy the full saved session history as JSON, for further processing outside the addon."
L["export_open_btn"]          = "Open Export Window"
L["export_title"]             = "Night's Farmtracker — Data Export"
L["copy_hint_window"]       = "Ctrl+C to copy"
L["export_select_all"]        = "Select All"
L["debug_title"]              = "Night's Farmtracker — Debug"

------------------------------------------------------------------------
-- German (deDE)
------------------------------------------------------------------------
if GetLocale() == "deDE" then
    L.MONTH_NAMES = {
        "Januar","Februar","März","April","Mai","Juni",
        "Juli","August","September","Oktober","November","Dezember",
    }
    L["start_tracking"]    = "Tracking starten"
    L["pause_tracking"]    = "Tracking pausieren"
    L["reset_session"]     = "Session zurücksetzen"
    L["reset_desc"]        = "In Verlauf speichern, Items & Timer leeren"
    L["reset_shift_hint"]  = "Shift-Klick: Zurücksetzen ohne Speichern im Verlauf"
    L["session_history"]   = "Session-Verlauf"
    L["settings"]          = "Einstellungen"
    L["collapse"]          = "Einklappen"
    L["expand"]            = "Ausklappen"
    L["close"]             = "Schließen"
    L["gathering_active"]  = "Sammle... Beute erscheint hier"
    L["help_categories"]   = "Kategorien:"
    L["help_cat_click"]    = "  Klick: ein-/ausklappen"
    L["help_cat_rclick"]   = "  Shift-Rechtsklick: ausschliessen"
    L["help_items"]        = "Gegenstände:"
    L["help_item_hover"]   = "  Hover: Tooltip anzeigen"
    L["help_item_rclick"]  = "  Shift-Rechtsklick: nicht tracken"
    L["help_gold"]         = "Gold-Übersicht:"
    L["help_gold_click"]   = "  Klick auf Gesamtgold (unten) zeigt Aufschlüsselung"
    L["help_reset"]        = "Zurücksetzen:"
    L["help_reset_shift"]  = "  Shift-Klick: Zurücksetzen ohne Speichern im Verlauf"
    L["help_histlog"]       = "Session-Verlauf / Verlaufsfenster:"
    L["help_histlog_left"]  = "  Linksklick: Session-Verlauf"
    L["help_histlog_right"] = "  Rechtsklick: Verlaufsfenster"
    L["help_filter"]        = "Filter / Blacklist:"
    L["help_filter_left"]   = "  Linksklick: Vendor-Only-Filter"
    L["help_filter_right"]  = "  Rechtsklick: Blacklist"
    L["help_title"]         = "Night's Farmtracker — Info"
    L["help_fishing"]       = "Angeln:"
    L["help_fishing_hint"]  = "  Venom-Tracker / Köder-Leiste in Einstellungen -> Angeln aktivieren"
    L["help_export"]        = "Datenexport:"
    L["help_export_hint"]   = "  Einstellungen -> Datenexport, oder /nft export"
    L["hist_log_left_hint"]  = "Linksklick: Session-Verlauf"
    L["hist_log_right_hint"] = "Rechtsklick: Verlaufsfenster"
    L["delete_session"]    = "Session löschen"
    L["delete_all"]        = "Alle Sessions löschen"
    L["clear_all"]         = "Alles löschen"
    L["reset_addon"]       = "Auf Standard zurücksetzen"
    L["reset_addon_confirm"] = "Das gesamte Addon auf Standard zurücksetzen? Dabei werden ALLE gespeicherten Daten gelöscht (Einstellungen, Session-Verlauf, Vendor-Only-Filter, Blacklist) und das kann nicht rückgängig gemacht werden. Die UI wird neu geladen."
    L["clear_all_history_confirm"] = "Gesamten gespeicherten Session-Verlauf löschen? Kann nicht rückgängig gemacht werden."
    L["no_sessions"]       = "Keine Sessions gespeichert"
    L["session_reset_migration_text"]  = "Night's Farmtracker zeigt im Tooltip jetzt das exakt gelootete Item an (korrekte Gegenstandsstufe bei skalierender Ausrüstung). Sessions, die vor diesem Update gespeichert wurden, haben diese Info nicht und zeigen bei Ausrüstung weiterhin einen generischen Tooltip.\n\nGesamten gespeicherten Session-Verlauf jetzt löschen, um neu zu starten?"
    L["tooltip_scaling_unknown"] = "Genaue Gegenstandsstufe unbekannt (vor diesem Update gespeichert)"
    L["item_singular"]     = "%d Item"
    L["item_plural"]       = "%d Items"
    L["tip_priced_ah"]     = "Mit AH-Preis berechnet: %d"
    L["tip_priced_vendor"] = "Mit Händlerpreis berechnet: %d"
    L["sessions_summary"]    = "%d Session"
    L["sessions_summary_pl"] = "%d Sessions"
    L["looted_gold"]       = "Direkt"
    L["merge_day_btn"]     = "Merge"
    L["merge_day_tooltip"] = "Alle Sessions dieses Tages zusammenführen"
    L["merge_day_confirm"] = "Alle %d Sessions von %s zusammenführen? Kann nicht rückgängig gemacht werden."
    L["month_summary_tooltip"] = "Shift-Klick: Monatsübersicht"
    L["detail_duration"]  = "Dauer"
    L["delete_month"]         = "Monat löschen"
    L["delete_month_confirm"] = "Alle %d Sessions von %s löschen? Kann nicht rückgängig gemacht werden."
    L["settings_title"]    = "Night's Farmtracker — Einstellungen"
    L["ah_source"]         = "AH-Preisquelle"
    L["ah_auto"]           = "Automatisch (beste verfügbare)"
    L["ah_auctionator"]    = "Auctionator"
    L["ah_oribos"]         = "Oribos Exchange"
    L["ah_tsm"]            = "TradeSkillMaster (TSM)"
    L["ah_none"]           = "Keine (nur Händlerpreis)"
    L["not_installed"]     = "(nicht installiert)"
    L["gear_ah_threshold_hint"] = "Ausrüstung nutzt den AH-Preis erst ab diesem Betrag, darunter wird der Händlerpreis gezeigt (0 = deaktiviert). Über das Zahnrad-Icon wählst du, für welche Ausrüstungs-Kategorien das gilt"
    L["gear_ah_threshold_sound"] = "Sound abspielen, wenn Ausrüstung diesen Betrag erreicht"
    L["gear_ah_threshold_config_title"] = "Schwelle gilt für:"
    L["gear_ah_threshold_config_tip"] = "Wähle, für welche Ausrüstungs-Kategorien die Schwelle gilt. Nicht angehakte Kategorien nutzen immer den höheren Wert aus AH- und Händlerpreis."
    L["gold_suffix"]       = "g"
    L["tsm_hint"]          = "Klicken zum Wechseln: DBMarket · DBRegionMarketAvg · DBMinBuyout"
    L["display"]           = "Anzeige"
    L["theme_default"]     = "Standard"
    L["theme_void"]        = "Void"
    L["theme_silvermoon"]  = "Silvermoon"
    L["theme_fel"]         = "Fel"
    L["theme_frost"]       = "Frost"
    L["theme_bloodmoon"]   = "Bloodmoon"
    L["theme_molten"]      = "Molten"
    L["theme_emerald"]     = "Emerald"
    L["theme_arcane"]      = "Arcane"
    L["theme_bronze"]      = "Bronze"
    L["theme_plague"]      = "Plague"
    L["theme_nether"]      = "Nether"
    L["theme_argent"]      = "Argent"
    L["theme_default_desc"]    = "Türkis"
    L["theme_void_desc"]       = "Lila"
    L["theme_silvermoon_desc"] = "Warmes Gold"
    L["theme_fel_desc"]        = "Giftgrün"
    L["theme_frost_desc"]      = "Eisblau"
    L["theme_bloodmoon_desc"]  = "Blutrot"
    L["theme_molten_desc"]     = "Lava-Orange"
    L["theme_emerald_desc"]    = "Smaragdgrün"
    L["theme_arcane_desc"]     = "Magenta"
    L["theme_bronze_desc"]     = "Bronze"
    L["theme_plague_desc"]     = "Kränkliches Grün"
    L["theme_nether_desc"]     = "Tiefes Türkis"
    L["theme_argent_desc"]     = "Heiliges Gold"
    L["gold_per_hour"]     = "Gold / Stunde"
    L["gold_per_min"]      = "Gold / Minute"
    L["session_length_hint"] = "Session-Länge: Der Timer zählt runter und pausiert automatisch bei 0 (0 = aus)"
    L["minutes_suffix"]    = "Min"
    L["session_length_reached"] = "Session-Länge erreicht - Tracking pausiert."
    L["session_length_reached_resume"] = "Session-Länge erreicht. Zurücksetzen für eine neue Session oder Länge in den Einstellungen ändern."
    L["gold_display_classic"] = "Klassische Gold-Anzeige (Icons)"
    L["gold_display_modern"]  = "Moderne Gold-Anzeige (farbiger Text)"
    -- Modern gold display suffixes
    L["coin_gold"]   = "g"
    L["coin_silver"] = "s"
    L["coin_copper"] = "k"
    L["minimap_button"]    = "Minimap-Button anzeigen"
    L["reload_required"]   = "Neustart erforderlich."
    L["cat_junk"]          = "Müll"
    L["junk_merged_name"] = "Plunder"
    L["cat_gear"]          = "Ausrüstung"
    L["cat_gear_boe"]      = "Ausrüstung (BoE)"
    L["cat_gear_boa"]      = "Ausrüstung (BoA)"
    L["cat_gear_soul"]     = "Ausrüstung (Seelengebunden)"
    L["cat_gear_cosmetic"] = "Ausrüstung (Kosmetisch)"
    L["cat_pets"]          = "Haustiere"
    L["cat_mounts"]        = "Reittiere"
    -- Tooltips
    L["cat_tip_click"]         = "Klick zum Ein-/Ausklappen"
    L["cat_tip_shift_rclick"]  = "Shift-Rechtsklick: Ausschliessen"
    L["item_tip_shift_rclick"] = "Shift-Rechtsklick: Nicht mehr tracken"
    -- Minimap
    L["mm_toggle"]   = "Klick zum Ein-/Ausblenden"
    L["mm_settings"] = "Rechtsklick für Einstellungen"
    L["mm_drag"]     = "Ziehen zum Verschieben"
    -- Gold rate suffix
    L["rate_hr"]  = "/Std"
    L["rate_min"] = "/Min"
    -- Gold overview tooltip
    L["gold_overview"] = "Gold-Übersicht"
    L["gold_items"]    = "Gegenstände"
    L["gold_total"]    = "Gesamt"
    -- Settings
    L["sec_categories"]          = "Kategorien & Gruppierung"
    L["sec_filters"]             = "Filter"
    L["session_history_enabled"] = "Session-Verlauf speichern"
    L["split_trade_goods"]       = "Handwerksmaterialien nach Typ aufteilen"
    L["split_gear_by_binding"]   = "Ausrüstung nach Bindung aufteilen (BoE/BoA/Seelengebunden)"
    L["merge_junk_entries"]      = "Müll zu einem Eintrag zusammenführen (\"Plunder\")"
    L["merge_daily_sessions"]    = "Sessions desselben Tages automatisch zusammenführen"
    L["session_history_mode"]         = "Session-Verlauf Modus:"
    L["session_history_mode_compact"] = "Kompakt (alte Monate zusammenfassen)"
    L["session_history_mode_full"]    = "Vollständig (jede Session behalten)"
    L["compact_history_confirm"]      = "Alle vergangenen Monate jetzt zu je einem Eintrag zusammenfassen? Das kann nicht rückgängig gemacht werden."
    L["vendor_filter_enabled"]   = "Vendor-Only-Filter aktivieren"
    L["blacklist_enabled"]       = "Blacklist aktivieren"
    L["log_window_enabled"]      = "Verlaufsfenster aktivieren"
    L["ah_auto_info"]            = "Bevorzugt Auctionator, dann Oribos Exchange, dann TSM"
    L["tsm_custom"]              = "Eigener TSM-Ausdruck (überschreibt oben)"
    L["sec_profiles"]            = "Profile"
    L["profile_new"]             = "Neu"
    L["profile_copy"]            = "Kopieren"
    L["profile_rename"]          = "Umbenennen"
    L["profile_delete"]          = "Löschen"
    L["profile_new_prompt"]      = "Name des neuen Profils:"
    L["profile_copy_prompt"]     = "Name der Kopie:"
    L["profile_rename_prompt"]   = "Profil umbenennen zu:"
    L["profile_delete_confirm"]  = "Profil \"%s\" löschen? Kann nicht rückgängig gemacht werden."
    L["profile_delete_hint"]     = "Ungenutztes Profil löschen (betrifft nicht dein aktives):"
    L["profile_delete_none"]     = "— keins —"
    -- Vendor-only filter
    L["filter_title"]            = "Vendor-Only-Filter"
    L["filter_button"]           = "Filter"
    L["filter_drop_hint"]        = "Gegenstand hier rein ziehen"
    L["filter_list_empty"]       = "Noch keine Items im Filter"
    L["filter_clear_all_confirm"] = "Alle Items aus dem Vendor-Only-Filter entfernen? Kann nicht rückgängig gemacht werden."
    L["filter_tip_shift_rclick"] = "  Shift-Rechtsklick: Entfernen"
    L["filter_categories_title"] = "Vendor-Only-Kategorien"
    L["filter_ah_expansions_title"] = "AH-Preis nach Expansion"
    L["filter_ah_expansions_hint"]  = "Expansions ankreuzen, für die AH-Preise angezeigt werden sollen. Nicht angekreuzte Expansions nutzen Vendor-Preis. Nichts angekreuzt = Filter aus."
    L["filter_left_hint"]        = "Linksklick: Vendor-Only-Filter"
    L["filter_right_hint"]       = "Rechtsklick: Blacklist"
    L["blacklist_title"]         = "Blacklist"
    L["blacklist_list_empty"]    = "Noch keine Items auf der Blacklist"
    L["blacklist_clear_all_confirm"] = "Alle Items von der Blacklist entfernen? Kann nicht rückgängig gemacht werden."
    L["blacklist_categories_title"] = "Blacklist-Kategorien"
    -- Verlaufsfenster
    L["log_title"]               = "Verlaufsfenster"
    L["log_empty"]                = "Noch keine Items"
    -- Angeln
    L["sec_fishing"]              = "Angeln"
    L["venom_tracker_enabled"]    = "Coiled-Huntress-Venom-Tracker aktivieren"
    L["venom_tracker_title"]      = "Venom Tracker"
    L["venom_tracker_hint"]       = "Ziehen zum Verschieben · Rechtsklick setzt zurück · /nft venom zum Umschalten"
    L["bait_frame_enabled"]       = "Angelköder-Leiste aktivieren"
    L["lockout_enabled"]          = "Instanz-Lockout-Zähler unter dem Hauptfenster anzeigen"
    L["lockout_count"]            = "Lockout: %d/%d"
    L["lockout_tooltip_title"]    = "Instanz-Lockout: %d/%d"
    L["lockout_reset_hint"]       = "Klicken, um Instanzen zurückzusetzen. Jeder Eintrag zeigt, wann er abläuft (1 Stunde nach dem Reset)."
    L["bait_frame_hint"]          = "Klick: benutzen · Rechtsklick: entfernen · Köder herziehen zum Hinzufügen"
    L["bait_frame_empty"]         = "Köder hierher ziehen zum Hinzufügen"
    L["bait_frame_rejected"]      = "Sieht nicht nach einem Angelköder aus. Umschalttaste halten, um trotzdem hinzuzufügen."
    L["bait_no_active_buff"]      = "Kein Köder aktiv"
    -- Datenexport
    L["sec_export"]               = "Datenexport"
    L["export_hint"]              = "Kopiert den gesamten gespeicherten Session-Verlauf als JSON zur weiteren Verwendung außerhalb des Addons."
    L["export_open_btn"]          = "Exportfenster öffnen"
    L["export_title"]             = "Night's Farmtracker — Datenexport"
    L["copy_hint_window"]       = "Strg+C zum Kopieren"
    L["export_select_all"]        = "Alles auswählen"
    L["debug_title"]              = "Night's Farmtracker — Debug"
end